# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Milian < Formula
  desc "Milian project."
  homepage "https://keyrotate.com/"
  version "0.0.5"
  license "BSD3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KeyRotate/milian/releases/download/v0.0.5/milian_0.0.5_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "a29162e880b5c6cf012f4dba749a8e8cea42636c228cafece0b59daccd12263d"

      def install
        bin.install "milian"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KeyRotate/milian/releases/download/v0.0.5/milian_0.0.5_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d3cafa756200ebd4e53b9439ac911ac683792afbced0d17e1e9c79c40e93b4ad"

      def install
        bin.install "milian"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/KeyRotate/milian/releases/download/v0.0.5/milian_0.0.5_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "6d3b5d7dd9fe4f3c906103d9bfde2f8777f91ad728bb247ed54e07e837cb858d"

      def install
        bin.install "milian"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KeyRotate/milian/releases/download/v0.0.5/milian_0.0.5_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "239cc7b99c43cc59322b7bbbd8aeeb02f0886a6d77a8933c169574d273fb86b3"

      def install
        bin.install "milian"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KeyRotate/milian/releases/download/v0.0.5/milian_0.0.5_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "0fddb2fd6262b8b2bb361022b82d0b51e5e00d8bbf7c5be2817b1b1e2b6f52e9"

      def install
        bin.install "milian"
      end
    end
  end

  test do
    system "#{bin}/milian version"
  end
end
