# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Milian < Formula
  desc "Milian project."
  homepage "https://keyrotate.com/"
  version "1.0.2"
  license "BSD3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/KeyRotate/milian/releases/download/v1.0.2/milian_1.0.2_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "128f3dfdd47168fc62a0600271438bbbc9be4bc3035356ccc1765fd64c6e91ee"

      def install
        bin.install "milian"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KeyRotate/milian/releases/download/v1.0.2/milian_1.0.2_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b6696168add50e44659f157242b9c2b67bb17021d49452c8ceff0bd7c462c008"

      def install
        bin.install "milian"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KeyRotate/milian/releases/download/v1.0.2/milian_1.0.2_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7085106b34414d0d9361d9d0f0b52583e4c683caf4755b584d7ad982d4664739"

      def install
        bin.install "milian"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KeyRotate/milian/releases/download/v1.0.2/milian_1.0.2_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "cfc32ea89e7fef774a199d4f7f4460e5fbdc03d6c37d861a10478ebcb3db9bb2"

      def install
        bin.install "milian"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/KeyRotate/milian/releases/download/v1.0.2/milian_1.0.2_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "3c8942e22917e2ad813f860d3132cf10e41b3bb7a21bbeb1fd7990f13816ce76"

      def install
        bin.install "milian"
      end
    end
  end

  test do
    system "#{bin}/milian version"
  end
end
